# Generated by Django 6.0.5 on 2026-05-31 17:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about/')),
                ('content', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'About Content',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(unique=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_name', models.CharField(max_length=200)),
                ('is_anonymous', models.BooleanField(default=False)),
                ('content', models.TextField()),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='6287863912739', max_length=20)),
                ('instagram_handle', models.CharField(default='@asari.bouquetflowerbdg', max_length=100)),
                ('tiktok_handle', models.CharField(default='@asari.bouquetflowerbdg', max_length=100)),
                ('address', models.TextField(default='Antapani, Bandung City')),
                ('low_stock_threshold', models.IntegerField(default=10)),
                ('order_template', models.TextField(default='🌼 FORMAT PEMESANAN ASARI FLORIST 🌼\nHaiii Kaaak! Silakan isi format di bawah ini yaaa 🤗\n(Catatan: Mohon tidak mengubah teks yang dicetak tebal agar pesanan cepat terproses sistem)\n\n📋 DETAIL PESANAN\n*Nama Produk:* {product_name}\n*Jumlah Produk:*\n*Request:*\n*Isi Kartu Ucapan (isi "-" jika kosongan):*\n*Jumlah Paper Bag (+2000) (isi "0" jika tidak pakai):*\n\n👤 INFORMASI PEMESAN\n*Nama Pemesan:*\n*No WhatsApp:*\n\n🚚 JADWAL & PENGIRIMAN\n*Tanggal Pengambilan (Contoh: Sabtu, 30 Mei 2026):*\n*Jam Pengambilan (Contoh: 12.30 WIB):*\n*Metode Penyerahan (Ketik: Ambil di Store / Diantar):*\n*Alamat Pengiriman (Kosongkan jika diambil di store):*')),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='SocialStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_followers', models.IntegerField(default=0)),
                ('prev_followers', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Social Stats',
            },
        ),
        migrations.CreateModel(
            name='SOPSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TermsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('is_featured', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='store.category')),
            ],
            options={
                'ordering': ['-is_featured', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('quantity', models.IntegerField(default=1)),
                ('request_notes', models.TextField(blank=True)),
                ('greeting_card', models.CharField(blank=True, default='-', max_length=500)),
                ('paper_bags', models.IntegerField(default=0)),
                ('customer_name', models.CharField(max_length=200)),
                ('customer_whatsapp', models.CharField(max_length=30)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('delivery_method', models.CharField(choices=[('pickup', 'Ambil di Store'), ('delivery', 'Diantar')], default='pickup', max_length=20)),
                ('delivery_address', models.TextField(blank=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('done', 'Done'), ('cancelled', 'Cancelled')], default='in_progress', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product')),
            ],
            options={
                'ordering': ['pickup_date', 'pickup_time'],
            },
        ),
        migrations.CreateModel(
            name='ProductDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='store.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ProductPerfectFor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(max_length=300)),
                ('order', models.IntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='perfect_for_items', to='store.product')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SOPItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('link_text', models.CharField(blank=True, max_length=100)),
                ('link_url', models.URLField(blank=True)),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.sopsection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TermsItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.CharField(blank=True, max_length=200)),
                ('content', models.TextField()),
                ('order', models.IntegerField(default=0)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='store.termssection')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
